name: modusgraph
channels:
  - pytorch3d
  - pytorch
  - iopath
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.5.7=py39h06a4308_0
  - cffi=1.15.1=py39h5eee18b_3
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=39.0.1=py39h9ce1e76_2
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.2.2=h20bf706_0
  - freetype=2.12.1=h4a9f257_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - giflib=5.2.1=h5eee18b_3
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.4=py39h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - iopath=0.1.9=py39
  - jpeg=9e=h5eee18b_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.17=h5eee18b_0
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libidn2=2.3.4=h5eee18b_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.0=h6a678d5_2
  - libunistring=0.9.10=h27cfd23_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - lz4-c=1.9.4=h6a678d5_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl-service=2.4.0=py39h5eee18b_1
  - mkl_fft=1.3.6=py39h417a72b_1
  - mkl_random=1.2.2=py39h417a72b_1
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.1.2=py39h06a4308_0
  - portalocker=2.7.0=py39hf3d152e_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=23.0.0=py39h06a4308_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.17=h955ad1f_0
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.4=py39_cu113_pyt1121
  - pyyaml=6.0=py39hb9d737c_4
  - readline=8.2=h5eee18b_0
  - requests=2.29.0=py39h06a4308_0
  - setuptools=67.8.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.8.0=hdb19cb5_0
  - termcolor=2.3.0=pyhd8ed1ab_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu113
  - torchvision=0.13.1=py39_cu113
  - tqdm=4.65.0=pyhd8ed1ab_1
  - typing_extensions=4.6.3=py39h06a4308_0
  - urllib3=1.26.16=py39h06a4308_0
  - wheel=0.38.4=py39h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xz=5.4.2=h5eee18b_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=h5eee18b_0
  - zstd=1.5.5=hc292b87_0
  - pip:
      - absl-py==1.4.0
      - appdirs==1.4.4
      - asttokens==2.2.1
      - backcall==0.2.0
      - cachetools==5.3.1
      - click==8.1.6
      - contourpy==1.0.7
      - cycler==0.11.0
      - cython==0.29.36
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - et-xmlfile==1.1.0
      - executing==1.2.0
      - fastgeodis==1.0.3
      - fonttools==4.39.4
      - gitdb==4.0.10
      - gitpython==3.1.32
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.56.0
      - imageio==2.29.0
      - importlib-metadata==6.8.0
      - importlib-resources==5.12.0
      - ipython==8.13.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.3.1
      - kiwisolver==1.4.4
      - lazy-loader==0.2
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - monai==1.2.0
      - natsort==8.3.1
      - networkx==3.1
      - nibabel==5.1.0
      - ninja==1.11.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - onnx==1.14.0
      - openpyxl==3.1.2
      - packaging==23.1
      - pandas==1.3.5
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - platformdirs==3.5.3
      - plotly==5.14.1
      - pooch==1.7.0
      - prompt-toolkit==3.0.38
      - protobuf==4.23.4
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pygments==2.15.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyvista==0.39.1
      - pywavelets==1.4.1
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scikit-image==0.20.0
      - scikit-learn==1.3.0
      - scipy==1.9.1
      - scooby==0.7.2
      - seaborn==0.12.2
      - sentry-sdk==1.28.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - stack-data==0.6.2
      - tenacity==8.2.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - threadpoolctl==3.1.0
      - tifffile==2023.4.12
      - torch-geometric==2.3.1
      - torch-geometric-temporal==0.54.0
      - torch-scatter==2.1.1
      - torch-sparse==0.6.17
      - traitlets==5.9.0
      - trimesh==3.21.7
      - tzdata==2023.3
      - vtk==9.2.6
      - wandb==0.15.5
      - wcwidth==0.2.6
      - werkzeug==2.3.6
      - zipp==3.15.0
prefix: /mnt/data/miniconda3/envs/modusgraph
